#!/bin/sh
while read file
do
        case "$1" in
        "d")
                rm "$file" ;;
        "c")
                echo -n "$file" | xclip -selection clipboard && wl-copy ;;
        "w")
               $HOME/bin/set-wall.sh  "$file" ;;
	    "p")
		    cat $file | xclip -selection clipboard -t image/png ;;
        esac
done
