#!/usr/bin/env bash

DMENU='dmenu -i -F -l 15 -p'
FZF='fzf --height 70% --border rounded --reverse --prompt'
terminal=foot

# have to add this function

menu() {
    printf "0. Play random songs\n"
    printf "1. Play A Song\n"
    printf "2. Play A Folder\n"
    printf "3. Play - Pause\n"
    printf "4. Play Next\n"
    printf "5. Play Prev\n"
    printf "6. Open ncmpcpp(Music palyer)\n"
    printf "7. Stop\n"
    printf "8. Current Song name\n"
    printf "9. volume 25 \n"
    printf "10. volume 50 \n"
    printf "11. volume 75 \n"
    printf "12. volume 100 \n"
}

playRandom() {
    mpc clear
    mpc add /
    mpc random on
    mpc play
}

play() {
    music=$(mpc listall | ${MENU} 'music to play > ')
    mpc clear 
    mpc -q add "$music"
    mpc play
    mpc repeat on
    dunstify "Playing" "$(mpc current)"
}

add() {
    music2=$(mpc listall | ${MENU} 'Add to queue > ')
    mpc -q add "$music2"
    dunstify "Added" "$(printf ${music2})"
}

FolderPlay() {
    folder=$(fd . /mnt/media/music/ --type directory | cut -b 18-1000 | ${MENU} 'Choose a Folder > ' )
    mpc stop
    mpc clear
    mpc add "${folder}"
    mpc repeat on
    mpc random off
    mpc play
    dunstify "Added" "$(printf ${folder})"
    dunstify "Playing" "$(mpc current)"
}


if [ $1 == '-f' ]
then
    MENU=${FZF}
else
    MENU=${DMENU}
fi

choose=$(menu | ${MENU} "choose your option > " | awk -F. '{ print $1 }')

case ${choose} in
    0)
	playRandom ;;
    1)
	play ;;
    2)
	FolderPlay ;;
    3)
	mpc toggle ;;
    4)
	mpc next
	dunstify "Playing" "$(mpc current)"
	;;
    5)
	mpc prev
	dunstify "Playing" "$(mpc current)"
	;;
    6)
	if [ $1 == '-f' ]
	then
	    ncmpcpp
	else
	    $terminal -e ncmpcpp
	fi
	;;
    7)
	mpc stop ;;
    8)
	dunstify "Playing" "$(mpc current)" ;;
    9)
	mpc volume 25 ;;
    10)
	mpc volume 50 ;;
    11)
	mpc volume 75 ;;
    12)
	mpc volume 100 ;;
    *)
	printf "Plece choose currect value"
esac
